/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kelompok1;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import java.util.ArrayList;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener; 
import java.text.SimpleDateFormat;
import javax.swing.Timer;
import java.util.Date;
import java.text.DateFormat;
import java.text.ParseException;
/**
 *
 * @author Asus X450J
 */
public class DataTransaksi extends javax.swing.JFrame {
Connection connj = null;
Connection conn = null;
ResultSet rsj = null;
PreparedStatement pstj = null;
ResultSet rs = null;
PreparedStatement pst = null;
ResultSet resultSet;
Statement statement;
DefaultTableModel tabelmodel;
inputbarang databarang;
String jenis, nama ,hapus ;

    /**
     * Creates new form DataTransaksi
     */

private void kondisiAwal() {
        edtotal.setText("0");
        edjenisbarang.setEnabled(false);
        ednota.setEnabled(false);
        ednonota.setEnabled(false);
        edtanggal.setEnabled(true);
        edhargabeli.setEnabled(false);
        edtanggal.setEnabled(false);
        }

private void waktu(){
    Date tgl = new Date();
    SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd");
    edtanggal.setText(s.format(tgl));
}
    
private void delete(){
        Connection conn = null;
        Statement stmt = null;
        String nama = ednamabarang.getText();
        try{
            conn = kelompok1.koneksidb.ConnectDb();
            stmt = conn.createStatement();
            stmt.executeUpdate("DELETE from tabeljual where NamaBarang=('"+nama+"');");
            //JOptionPane.showMessageDialog(this, rs);
            JOptionPane.showMessageDialog(null, "Data Berhasil Di Hapus");
            rs = pst.executeQuery();
            //tabeljual.setModel(DbUtils.resultSetToTableModel(rs));
            hapus();
            ednamabarang.requestFocus();
        }catch (Exception t){
            JOptionPane.showMessageDialog(null, "Data Gagal Di Hapus !");
        }
        
    }
    private void ResetTabel()
{
    try
    {
        String sql = "select Kode,JenisBarang,Nama,HargaBeli,Harga,Unit,Total from datapenjualan where nota= '"+ednota.getText()+"';";
        pst = conn.prepareStatement(sql);
        rs = pst.executeQuery();
        tabeljual.setModel(DbUtils.resultSetToTableModel(rs));
    }
    catch (Exception e)
    {
        JOptionPane.showMessageDialog(null, e);           
    }
}

    public DataTransaksi() {
        initComponents();
        connj = kelompok1.koneksidb.ConnectDb();
        conn = kelompok1.koneksidb.ConnectDb();
       // UpdateTable();
        kondisiAwal();
        ResetTabel();
        buatnomor();
        setJam();
        databarang = new inputbarang();
        setTitle("Transaksi");
        waktu();
    }
 
    private void hapus(){
        edcode.setEnabled(true);
        edcode.setText("");
        edharga.setText("");
        ednamabarang.setText("");
        edunit.setText("");
        edjenisbarang.setText("");
        edtotal.setText("");
        edcode.requestFocus();
        edstok.setText("");
        edhargabeli.setText("");
    }
     public void setJam(){
    ActionListener taskPerformer = new ActionListener() {

    public void actionPerformed(ActionEvent evt) {
    String nol_jam = "", nol_menit = "",nol_detik = "";

    java.util.Date dateTime = new java.util.Date();
    int nilai_jam = dateTime.getHours();
    int nilai_menit = dateTime.getMinutes();
    int nilai_detik = dateTime.getSeconds();

    if(nilai_jam <= 9) nol_jam= "0";
    if(nilai_menit <= 9) nol_menit= "0";
    if(nilai_detik <= 9) nol_detik= "0";

    String waktu = nol_jam + Integer.toString(nilai_jam);
    String menit = nol_menit + Integer.toString(nilai_menit);
    String detik = nol_detik + Integer.toString(nilai_detik);

    edjam.setText(waktu+":"+menit+":"+detik+"");
    }
};
    new Timer(1000, taskPerformer).start();
}
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField3 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        edcode = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ednamabarang = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        edunit = new javax.swing.JTextField();
        edreset = new javax.swing.JButton();
        edharga = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        edtotal = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabeljual = new javax.swing.JTable();
        edbayar = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        ednota = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        edjenisbarang = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        ednonota = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        edjam = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        edcari = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        edhargabeli = new javax.swing.JTextField();
        edtanggal = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        edstok = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        edtotal1 = new javax.swing.JTextField();

        jLabel7.setText("jLabel7");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setText("Nota");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Old English Text MT", 0, 36)); // NOI18N
        jLabel1.setText(" Data Transaksi");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText(" Kode");

        edcode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                edcodeFocusGained(evt);
            }
        });
        edcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edcodeActionPerformed(evt);
            }
        });
        edcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                edcodeKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                edcodeKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText(" Nama Barang");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Harga");

        ednamabarang.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText(" Unit");

        edunit.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                edunitFocusGained(evt);
            }
        });
        edunit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edunitActionPerformed(evt);
            }
        });
        edunit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                edunitKeyTyped(evt);
            }
        });

        edreset.setText("Reset");
        edreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edresetActionPerformed(evt);
            }
        });

        edharga.setEnabled(false);

        jButton1.setText("Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        edtotal.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Old English Text MT", 1, 36)); // NOI18N
        jLabel5.setText("Rp.");

        tabeljual.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabeljual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabeljualMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabeljual);

        edbayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edbayarActionPerformed(evt);
            }
        });
        edbayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                edbayarKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("Bayar");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setText("Nota");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel12.setText("Jenis Barang");

        edjenisbarang.setEnabled(false);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel13.setText("Nota Ke");

        ednonota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ednonotaActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel14.setText("Tanggal");

        edjam.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        edjam.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        edjam.setToolTipText("");
        edjam.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel15.setText("Pencarian");

        edcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edcariActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText(" Harga Beli");

        edhargabeli.setEnabled(false);

        edtanggal.setEnabled(false);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel16.setText("Jumlah Stok");

        edstok.setEnabled(false);
        edstok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edstokActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel17.setText("Total");

        edtotal1.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edtotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(edbayar, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(edtotal1))
                                .addGap(8, 8, 8))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ednamabarang, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(edcode, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(4, 4, 4)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(edhargabeli)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(edunit, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(edreset)))))))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                                        .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(edjenisbarang)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(edtanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 84, Short.MAX_VALUE))
                                    .addComponent(edstok)
                                    .addComponent(edharga)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(102, 102, 102)
                                .addComponent(edjam, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ednota, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ednonota, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edcari)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(edjam, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ednonota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ednota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(edharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ednamabarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edjenisbarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(edstok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edhargabeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edunit)
                    .addComponent(edreset)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edtanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(edtotal, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(edtotal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edbayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void edresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edresetActionPerformed
        // TODO add your handling code here:
        edunit.setText("");
        edtotal.setText("");
        edcode.setText("");
        ednamabarang.setText("");
        edharga.setText("");        
        edcode.requestFocus();
        edjenisbarang.setText("");
        edcode.setEnabled(true);
    }//GEN-LAST:event_edresetActionPerformed
     
    public void buatnomor(){
        try{
            conn = kelompok1.koneksidb.ConnectDb();
            Statement stmt = conn.createStatement();
            String sql = "select nota as nota from datapenjualan ORDER by nota desc";
            rs = stmt.executeQuery(sql);
            if (rs.next()){
                int no_t = Integer.parseInt(rs.getString("nota"))+1;
                ednota.setText(Integer.toString(no_t));
            }
            else{
                int no_t = 1;
                ednota.setText(Integer.toString(no_t));
            }
            rs.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Menu w = new Menu();
        w.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void edunitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edunitActionPerformed
        // TODO add your handling code here:
        if (edunit.getText().equals("")){
        JOptionPane.showMessageDialog(rootPane, "Data Belum Lengkap !");
        edcode.requestFocus();
        edcode.setEnabled(true);
    }
    else{
        Connection conn = null;
        Statement stmt = null;
        int stoksekarang , unit, total,harga;
        stoksekarang = Integer.valueOf(edstok.getText());
        unit = Integer.valueOf(edunit.getText());
        harga = Integer.valueOf(edharga.getText());
        if (stoksekarang<unit){
            JOptionPane.showMessageDialog(null, "Stok tidak cukup!");
        }
        else{
            total=unit*harga;
            edtotal.setText(""+total);
            String nota = ednota.getText();
            String Kode=edcode.getText();
            String JenisBarang=edjenisbarang.getText();
            String Nama=ednamabarang.getText();
            String HargaBeli=edhargabeli.getText();
            String Harga=edharga.getText();
            String Unit=edunit.getText();
            String Total=edtotal.getText();  
            String Tanggal=edtanggal.getText();
            int akhirstok = stoksekarang-unit;
            String stotalstok=String.valueOf(akhirstok);
            String updatetabel ="UPDATE databarang" + " SET Stok = '" +stotalstok+ "' WHERE kode = '"+edcode.getText()+"'";
            try{
                conn = kelompok1.koneksidb.ConnectDb();
                stmt = conn.createStatement();
                stmt.executeUpdate("insert into datapenjualan values('"+Tanggal+"','"+Kode+"','"+JenisBarang+"','"+Nama+"','"+HargaBeli+"','"+Harga+"','"+Unit+"','"+Total+"','"+nota+"')");   
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
       try{
                stmt.execute(updatetabel);
                edstok.setText(stotalstok);
                hapus();
                int nonota= Integer.valueOf(ednonota.getText());
                nonota++;
                String snonota= String.valueOf(nonota);
                ednonota.setText(snonota);
                ResetTabel();
                waktu();
                String sql_total = "SELECT sum(total) from datapenjualan where nota ='"+ednota.getText()+"'";
                ResultSet rsstotal = stmt.executeQuery(sql_total);
                while (rsstotal.next()){
                    edtotal.setText(rsstotal.getString(1));
                    edtotal1.setText(edtotal.getText());
                }  
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            } 
        }
    }
    }//GEN-LAST:event_edunitActionPerformed
    
    private void edcodeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edcodeFocusGained
        // TODO add your handling code here:
        if(ednonota.getText().equals("")){
            ednonota.setText("1");
        }
    }//GEN-LAST:event_edcodeFocusGained

    private void edcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edcodeActionPerformed
        // TODO add your handling code here:
        Connection conn = null;
        Statement stmt = null;
        
        String id = edcode.getText();
        
        try
        {
            conn = kelompok1.koneksidb.ConnectDb();
            stmt = connj.createStatement();
            String query = "select JenisBarang from databarang where kode= '"+id+"';";
            ResultSet rss =stmt.executeQuery(query);
            while (rss.next())
            {
                edjenisbarang.setText(rss.getString("JenisBarang"));
            }
            query = "select Harga from databarang where kode= '"+id+"';";
            ResultSet Hargaa =stmt.executeQuery(query);
            while (Hargaa.next())
            { 
                edharga.setText(Hargaa.getString("Harga"));
            }
            query = "select Nama from databarang where kode= '"+id+"';";
            ResultSet Namaa =stmt.executeQuery(query);
            while (Namaa.next())
            { 
                ednamabarang.setText(Namaa.getString("Nama"));
            }
            query = "select HargaBeli from databarang where kode= '"+id+"';";
            ResultSet HargaBelii =stmt.executeQuery(query);
            while (HargaBelii.next())
            { 
                edhargabeli.setText(HargaBelii.getString("HargaBeli"));
            }
            query = "select Stok from databarang where kode= '"+id+"';";
            ResultSet Stokk =stmt.executeQuery(query);
            while (Stokk.next())
            { 
                edstok.setText(Stokk.getString("Stok"));
            }
            
            edunit.requestFocus();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_edcodeActionPerformed

    private void edcodeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edcodeKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_edcodeKeyTyped

    private void edunitKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edunitKeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();  
        if(!(((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE)))){  
            getToolkit().beep();  
            evt.consume();  
        }
    }//GEN-LAST:event_edunitKeyTyped

    private void edbayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edbayarActionPerformed
        // TODO add your handling code here:
        if (edbayar.getText().equals("")){
        JOptionPane.showMessageDialog(rootPane, "Harap Masukkan Uang Anda !");
        edcode.setText("");
        edbayar.requestFocus();
    }
    else{
        double total = Double.valueOf(edtotal.getText());
        double bayar = Double.valueOf(edbayar.getText());
        double kembalian = bayar - total;
        if (kembalian >= 0){
            edtotal.setText(String.valueOf(kembalian));
            JOptionPane.showMessageDialog(rootPane, "Total Belanja Anda = Rp. "+edtotal1.getText() + "\nUang Anda = Rp. "+edbayar.getText() + "\nKembaliannya = Rp. "+kembalian);
            JOptionPane.showMessageDialog(rootPane, "  TERIMA KASIH  ");
            hapus();
            edbayar.setText("");
            ednonota.setText("1");
            edtotal.setText("");
            edtotal1.setText("");
            edcode.requestFocus();
            buatnomor();
            ResetTabel();
        }
        else{
            JOptionPane.showMessageDialog(rootPane, " GA PUNYA DUIT GAUSAH KE SINI ! ");
        }
    }
    }//GEN-LAST:event_edbayarActionPerformed

    private void edcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edcariActionPerformed
        // TODO add your handling code here:
        Connection conn = null;
        Statement stmt = null;
        String Kode = edcode.getText();
        String Nama = ednamabarang.getText();
        String JenisBarang = edjenisbarang.getText();
        String HargaBeli = edharga.getText();
        edcode.setText(Kode);
        
        String nm = ednamabarang.getText();
        String cari = edcari.getText();
        try
        {
            conn = kelompok1.koneksidb.ConnectDb();
            stmt = connj.createStatement();
            String query = "select JenisBarang from databarang where Nama= '"+cari+"';";
            ResultSet rss =stmt.executeQuery(query);
            while (rss.next())
            {
                edjenisbarang.setText(rss.getString("JenisBarang"));
            }
            query = "select Harga from databarang where Nama= '"+cari+"';";
            ResultSet Hargaa =stmt.executeQuery(query);
            while (Hargaa.next())
            { 
                edharga.setText(Hargaa.getString("Harga"));
            }
             query = "select Nama from databarang where Nama= '"+cari+"';";
            ResultSet Namaa =stmt.executeQuery(query);
            while (Namaa.next())
            { 
                ednamabarang.setText(Namaa.getString("Nama"));
            }
            query = "select Kode from databarang where Nama= '"+cari+"';";
            ResultSet Kodee =stmt.executeQuery(query);
            while (Kodee.next())
            { 
                edcode.setText(Kodee.getString("Kode"));
            }
            query = "select HargaBeli from databarang where Nama= '"+cari+"';";
            ResultSet HargaBelii =stmt.executeQuery(query);
            while (HargaBelii.next())
            { 
                edhargabeli.setText(HargaBelii.getString("HargaBeli"));
            }
            query = "select Stok from databarang where Nama= '"+cari+"';";
            ResultSet Stokk =stmt.executeQuery(query);
            while (Stokk.next())
            { 
                edstok.setText(Stokk.getString("Stok"));
            }
            edcari.setText("");
            edunit.requestFocus();
            edcode.setEnabled(false);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
            JOptionPane.showMessageDialog(null, "Data Tidak Tersedia");
        }
        
    }//GEN-LAST:event_edcariActionPerformed
    
    private void edbayarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edbayarKeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();  
        if(!(((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE)))){  
            getToolkit().beep();  
            evt.consume();  
        }
    }//GEN-LAST:event_edbayarKeyTyped

    private void edcodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edcodeKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_edcodeKeyPressed

    private void ednonotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ednonotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ednonotaActionPerformed

    private void edunitFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edunitFocusGained
        // TODO add your handling code here:
       if(ednonota.getText().equals("")){
            ednonota.setText("1");
        }
    }//GEN-LAST:event_edunitFocusGained

    private void edstokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edstokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edstokActionPerformed
int brs;
    private void tabeljualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabeljualMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount()==1){
        brs=tabeljual.rowAtPoint(evt.getPoint());
        edcode.setText(tabeljual.getValueAt(brs, 0).toString());
        edjenisbarang.setText(tabeljual.getValueAt(brs, 4).toString());
        ednamabarang.setText(tabeljual.getValueAt(brs, 1).toString());
        edhargabeli.setText(tabeljual.getValueAt(brs, 2).toString());
        edharga.setText(tabeljual.getValueAt(brs, 3).toString());
        edstok.setText(tabeljual.getValueAt(brs, 5).toString());
        }
    }//GEN-LAST:event_tabeljualMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataTransaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField edbayar;
    private javax.swing.JTextField edcari;
    private javax.swing.JTextField edcode;
    private javax.swing.JTextField edharga;
    private javax.swing.JTextField edhargabeli;
    private javax.swing.JLabel edjam;
    private javax.swing.JTextField edjenisbarang;
    private javax.swing.JTextField ednamabarang;
    private javax.swing.JTextField ednonota;
    private javax.swing.JTextField ednota;
    private javax.swing.JButton edreset;
    private javax.swing.JTextField edstok;
    private javax.swing.JTextField edtanggal;
    private javax.swing.JLabel edtotal;
    private javax.swing.JTextField edtotal1;
    private javax.swing.JTextField edunit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTable tabeljual;
    // End of variables declaration//GEN-END:variables
//int baris = 0;
//static Object kolom[] ={"Tanggal","Kode","JenisBarang","Nama","Harga","Unit","Total"};
//DefaultTableModel mdl = new DefaultTableModel(kolom,baris);

private void close(){
    WindowEvent winClosing = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
    Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosing);
}
}
